---
title: "MASTER Géomatique - USSEIN"
subtitle: "Semaine du 19 au 23 février 2024"
author: "Hugues Pecout (CNRS, UMR Géographie-Cités)"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


\


## Programme et matériel


\

#### Lundi 19 février : **Introduction à la cartographie thématique & au logiciel Magrit** 

\

Rappel des fondamentaux : [https://huguespecout.github.io/Intro_carto_thematique/](https://huguespecout.github.io/Intro_carto_thematique/)

Logiciel Magrit : [https://magrit.cnrs.fr/](https://magrit.cnrs.fr/)

\
\

#### Du Mardi 20 au Vendredi 23 février : **Géomatique & cartographie avec R**

\

Supports de cours :

- **Géomatique avec R** : [https://rcarto.github.io/geomatique_avec_r/](https://rcarto.github.io/geomatique_avec_r/){target="_blank"}     
- **Cartographie avec R** : [https://rcarto.github.io/cartographie_avec_r/](https://rcarto.github.io/cartographie_avec_r/){target="_blank"}    

\

Exercices :

- ***Exercice 1*** - Cartographie avec mapsf : [https://github.com/HuguesPecout/GeoExo_Carto_R](https://github.com/HuguesPecout/GeoExo_Carto_R){target="_blank"}    
- ***Exercice 2*** - Manipulation de données vectorielles :[https://github.com/HuguesPecout/GeoExo_sf_R](https://github.com/HuguesPecout/GeoExo_sf_R){target="_blank"}      
- ***Exercice 3*** - R, OpenStreetMap et OSRM :[https://github.com/HuguesPecout/GeoExo_osm_R](https://github.com/HuguesPecout/GeoExo_osm_R){target="_blank"}    

\
\
\


## Ressources supplémentaires

\

#### Sites web :

**Rzine** - Ressources diverses sur la pratique de R en SHS (et géomatique) : [https://rzine.fr/](https://rzine.fr/){target="_blank"}         
**ElementR** - Groupe d'utilisateurs pour le traitement de l'information Géographique avec R : [https://elementr.netlify.app/](https://elementr.netlify.app/){target="_blank"} 

\

#### Supports de formation :

**Cartographie thématique avec Magrit** : [https://github.com/magrit-formations](https://github.com/magrit-formations){target="_blank"}        
**Représentation graphique avec R**  : [https://huguespecout.github.io/SO_MATE_2023/](https://huguespecout.github.io/SO_MATE_2023/){target="_blank"}        
**Document computationnel avec R** : [https://elementr.gitpages.huma-num.fr/session_notebook/programmation_lettree/](https://elementr.gitpages.huma-num.fr/session_notebook/programmation_lettree/){target="_blank"}        



\
\
\
\
\

\

<center>
Github : [https://github.com/HuguesPecout](https://github.com/HuguesPecout){target="_blank"}               
GitLab : [https://gitlab.huma-num.fr/hpecout](https://gitlab.huma-num.fr/hpecout){target="_blank"}    
</center>


